#!/usr/bin/env bash
# sync-skills.sh - keep the Codex skills mirror and the plugin manifest honest.
#
#   ./_ops/sync-skills.sh          # mirror + regenerate
#   ./_ops/sync-skills.sh --check  # exit non-zero on any drift
#
# TWO JOBS:
#
# 1. Mirror .claude/skills/ to .agents/skills/ VERBATIM. No string substitution,
#    ever. Skills are model-neutral prose: nothing inside one should say
#    "Claude" or "Codex" in the first place. A blind find-replace of the tool
#    name across a mirror once produced a broken copy that referenced a model
#    that did not exist and paths that went nowhere, and it was not caught for
#    weeks because nothing compared the two trees. A dumb copy plus a daily
#    --check is the whole fix.
#
#    Both trees are exactly the same depth, so a relative link inside a skill
#    resolves identically from either one. The skill promotion gate in the daily
#    routine verifies that rather than assuming it.
#
# 2. Regenerate .claude-plugin/plugin.json from the actual folder listings, so
#    the manifest cannot drift from what is on disk. Never hand-edit it.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

MODE="${1:-write}"
SRC=.claude/skills
DST=.agents/skills
MANIFEST=.claude-plugin/plugin.json

render_manifest() {
  python3 - <<'PY'
import json, os

def listing(path, want_dirs):
    if not os.path.isdir(path):
        return []
    names = []
    for n in sorted(os.listdir(path)):
        if n.startswith((".", "_")):
            continue
        full = os.path.join(path, n)
        if want_dirs and os.path.isdir(full):
            names.append(n)
        elif not want_dirs and os.path.isfile(full) and n.endswith(".md"):
            names.append(n)
    return names

skills = listing(".claude/skills", True)
commands = listing(".claude/commands", False)

# Identity comes from config.yaml, which the whole OS treats as the only place
# environment-specific values live. Hardcoding it here would mean the daily
# drift check silently reverts an adopter's edit every morning.
def cfg(key, default):
    try:
        for line in open("config.yaml", encoding="utf-8"):
            if line.startswith(key + ":"):
                return line.split(":", 1)[1].split("#")[0].strip().strip('"\'')
    except OSError:
        pass
    return default

repo_name = cfg("repo_name", "team-os")
company = cfg("company_name", repo_name)

manifest = {
    "$schema": "https://json.schemastore.org/claude-code-plugin.json",
    "name": repo_name,
    "version": "1.0.0",
    "description": (
        f"{company} Team OS skills: "
        + ", ".join(skills)
        + ". GENERATED by _ops/sync-skills.sh from the skills and commands folders; do not hand-edit."
    ),
    "author": {"name": company},
    "skills": "./.claude/skills",
    "commands": ["./.claude/commands/" + c for c in commands],
}
print(json.dumps(manifest, indent=2) + "\n", end="")
PY
}

if [[ "$MODE" == "--check" ]]; then
  fail=0
  # -x .DS_Store or this deadlocks: rsync refuses to copy it, diff insists on
  # comparing it, and the fixer can never satisfy the checker. On a Shared Drive
  # that people open in Finder, .DS_Store is a certainty.
  if ! diff -rq -x .DS_Store "$SRC" "$DST" >/dev/null 2>&1; then
    echo "sync-skills: DRIFT - the mirror does not match the canonical skills" >&2
    diff -rq -x .DS_Store "$SRC" "$DST" >&2 || true
    fail=1
  fi
  if ! diff -q <(render_manifest) "$MANIFEST" >/dev/null 2>&1; then
    echo "sync-skills: DRIFT - $MANIFEST is stale" >&2
    fail=1
  fi
  [[ $fail -eq 0 ]] && echo "sync-skills: in sync"
  exit $fail
fi

mkdir -p "$DST" "$(dirname "$MANIFEST")"
if command -v rsync >/dev/null 2>&1; then
  rsync -a --delete --exclude '.DS_Store' "$SRC/" "$DST/"
else
  # rsync is missing from plenty of slim Linux and CI images, and this script is
  # the documented fix for a drift the daily routine reports. It must not be the
  # thing that cannot run.
  rm -rf "$DST"
  mkdir -p "$DST"
  (cd "$SRC" && find . -name .DS_Store -prune -o -type f -print) \
    | while IFS= read -r f; do
        mkdir -p "$DST/$(dirname "$f")"
        cp "$SRC/$f" "$DST/$f"
      done
fi
render_manifest > "$MANIFEST"
echo "sync-skills: mirrored $SRC -> $DST and regenerated $MANIFEST"
